### ISSUE TITLE
Example of 'hidden_test.csv' format for input file

### ISSUE THREAD

**Issue by GenTxt** [orzhan/rusimscore#1]
Have model and readme example working but encountering error when trying to read a 'one line - one sentence' .txt file

File "generate.py", line 147, in <module>
    for i, line in tqdm(f):
ValueError: too many values to unpack (expected 2))

Could you please provide the 'hidden_test.csv' and/or example of the .csv format used.

Cheers

**Comment by orzhan** [comment]
There was a bug in the file parser, please check the updated version. I've also added an example of an input file

**Comment by GenTxt** [comment]
Works 100% now. Closing issue.

Cheers
